-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgueM7k8RZF/P5FTKQ
NAVj/D/Qx9coFJfPWcDNH2mAfqugCgYIKoZIzj0DAQehRANCAASsilbPGHWD/37u
t7wSgnuE9H/kbAynTN5Cz7TS0WH5Wk/56JfLhNTqRxL8twxZGUPFS3KZ0VlCzCUw
AODDgex2
-----END PRIVATE KEY-----