-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg57OWWAwxJifpGriO
k2ALsFQDJhNigxnQYxe0EaL5/pmgCgYIKoZIzj0DAQehRANCAARRLOgZP8F7f8Es
1speMlSBVMKrd2abmXaW4dUKPr34a3BJFdir/5QCdgmkxRl6kHTRX1XGmJ7jvMM+
GSe6nnRL
-----END PRIVATE KEY-----