# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
skip_docs

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do

    # app_store_connect_api_key
    # get_provisioning_profile

    # increment_build_number(
    #     xcodeproj: "github-actions-demo-ios.xcodeproj",
    #     build_number: date_based_build_number
    # )

    # build_app(
    #     scheme: "github-actions-demo-ios",
    #     configuration: "Release"
    # )
    # upload_to_testflight(skip_waiting_for_build_processing: true)
    

    sync_code_signing(type: "appstore", git_private_key: "-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-128-CBC,39875A239A7ED234B1D764E982F8C023

uwakGc/1EcqpbMlfBaDOLK8E6P/ZlH1So1EQloWqg+xMzYXK8BWjsbPrahoNboVg
KoIGXpLeGuWHtXjNogCgwIs6l+CAiJRkZzi9Vxz6Fl4RRocHR5RIlMr/eQJOqnth
D000N9dOv4z1v7u9kvscxh95UEBiZk5CJZSnFfWL4txVQTSv1bDDIyUGcvGREsCm
7kMiivlp0vdzM1KEAQej1T4f2NhBn+pmx32G15YMqv6MInJVZystOLe4EfbANyIJ
T5Isd5w3vvVhmZq/PW8JabJW2DbgRuJ4rqZkOZi3tfQC9Sbt3lRIkIK6iU4xbcEB
h5S1UMiGmhe+u7EWdIR1DORnd+KQv8iU/goRBukHnFNV7fsm3hAZJIGVp4bSfDB7
CNuKhngTtz/RIX5dVhfLQcAuhV7zlj8SvuQmOhvzSVJ5XSF8JxagfsA+lGwFxjlP
8LKK8ocidaR3YofGMEI9MH0qF/FNNvnMM2yx7ZPZqKDaIYquAy/yhw7XpElxCXc6
ou0dKmky5FnEucI9FCesjlvkoQpBXGWcl1urWO0vhH/92jwF8qzLnWKUR7IvztqQ
sMepdzTpAmAoKVKjww6tPXj5YN0f2Y5/IEW3PI9FC1DAay1dIAJpk8KhT7CpfPdU
ETiF+BH6Sm8U9CNiqP6PLTVrX9hkQSDdYT1TBLRhjYfLQCpM1etJj6bnsHb85yAW
o9a5Lt6Mcy9ZsDvUKGGOJkCqU9K5KIy1BObQoub1QemMrSKGgOnhZ3VRt09JsUQ/
6jT7tHpZtfpxwW7pLTAXpYAbFj06bYTzSmgVo0BIYlW0yxlKizTQ9ZvpyLv5AnHt
zh0NmqxvsNnk/XUvLJm+pgadv3aO7Jkh9mP02N1wHOMUfivwjGSMY+PxulIdX1rP
XZYVZC/i6+MdaDu3dyL+pXHIwCY/Kve6ETgEnu4osskqOaqEVfe7mXF9/nv0dVwO
vaFSPvsdYLeJZkHzpZwDhKCumd5gnhd72QBHmEUuYpP1FPVAPr1ntAH914r0lX86
gA7MLFc1vdf5mLz7pFvHPWVbIeykqUlwJndaTOOZp7ZNkPWVKMI1R6z+fLhN7v34
5pDs9ObnyG/52IsXYKxNDPp2YWHTb3pPY/Z7iL8DRD2k406IJSEP21E42aI6wb82
GxWCBLI2ckW4xKU4YdzgCLDtZCKCcds9vAWOPj7QraLkYDqhuc2xYFipSstVfG7h
9AweTFHE5EbWKEVFYto7vHn0Qi0sfjn2/vtdh0bJimJGC78q3jGpbZqruZPx0rAU
95SUPiCpzzAtxSMM2bjGsoKYDEXn6tnp48FG6QyKx1Qlgob80aWC7NeqZZuGchIF
nj8k5KCNg2DUh5bwgUkzyASBgxwp8AkCy0Yuj5ggOygotLg9Q8s+xuxxQAW4hnPi
zjbUW7Iw55RjHhzOFWbFdH0hzisTmoCvk1BUzI9XSGbl+zpZoGjCWkhNPxMwUQVa
FWnGzp3aNVp+I12QG936A7BKX8AcmxqpLeHJP+Ftp+svN0xJH5vC5yeqdiZQ2y5Y
vqrrOJpJeJGbi6rUladJ5K8dedetgVIGBqVH7Vg6xCTVWuBSAiqMf7dSh9OSItm2
-----END RSA PRIVATE KEY-----
") 

    # 安装所有的Cocoapods依赖
    cocoapods()

    # 增加构建号
    increment_build_number(
        xcodeproj: "github-actions-demo-ios.xcodeproj",
        build_number: date_based_build_number
    )


    # 构建你的应用
    build_app(
      scheme: "github-actions-demo-ios",
      clean: true,
      export_method: "app-store",
      output_directory: "./build"
    )

    # 发布到TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )


  end
end

def today_formatted
  Date.today.strftime('%Y%m%d')
end

def default_build_number
  "#{today_formatted}01"
end

def date_based_build_number
  current_build_number = get_build_number(xcodeproj: "buildandgrow-app-ios.xcodeproj")

  build_date = current_build_number[0..7]
  build_version = current_build_number[8..9]

  if (!build_date || !build_version) || (build_date.empty? || build_version.empty?)
    return default_build_number
  end

  begin
    build_date_object = Date.strptime(build_date, '%Y%m%d')
  rescue
    return default_build_number
  end


  if build_date_object >= Date.today
    new_version = build_version.to_i + 1
    return "#{today_formatted}%02d" % new_version
  end

  return default_build_number
end
