# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
skip_docs




platform :ios do

  # 定义一个全局变量api_key，下面都会要用到这个 api_key
  # key_id 和 issuer_id 都可以在 AppStoreConnect后台 -> 用户和访问 -> 秘钥 这里找到
  api_key = app_store_connect_api_key(
      key_id: "29GV9Y24TJ",
      issuer_id: "dd8720fa-81f1-4700-8c0c-e44dc6cb03ab",
      key_filepath: "fastlane/AuthKey_29GV9Y24TJ.p8", # 上面下载的p8文件路径
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
  )

# fastlane run app_store_connect_api_key  key_id:"29GV9Y24TJ" issuer_id:"dd8720fa-81f1-4700-8c0c-e44dc6cb03ab" key_filepath:"AuthKey_29GV9Y24TJ.p8"
  
  desc "下载所有需要的证书和描述文件到本地，不会重新创建证书和描述文件（只读方式）"
  lane :match_all do
      # match(api_key: api_key, type: "development", readonly: true)
      # match(api_key: api_key, type: "adhoc", readonly: true)
      match(api_key: api_key, type: "appstore", readonly: true)
  end

  lane :release do
      # 先同步appstore证书和描述文件
      match(api_key: api_key, type: "appstore", readonly: true, git_private_key: "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAQEAxvgDYzJz6Q9K+Mescp9H7SeVAT5ztcjR3FiOd5asWDg7hgWGsEIW
UbKvegYnIGkTs2LKm1f5U0puvDgIKOaLK0CDgImwxdi7HsPYIzqAdraMM/QiOD6TJ8Mt2Y
yiSviwNDd6VcwpH3/bcG8YxD+drkoU58Gh8HJeMhrludyQW0ztn+xtKd0L0MUaAdoArCDs
0WCLwOCDm08YXavgKmAzuCNq6TBv54NyXofGdGZgeqF4zK6a5HyZ7h2C8M7HbRFRFmOiYn
Sfbv4geCobOz9YD14DrTAo/JVZ9WdNlEA/5SOvGJ8GG8IwwfFsABd777sMNlNDc6B/o2cd
kCUydSQypQAAA9A76y8UO+svFAAAAAdzc2gtcnNhAAABAQDG+ANjMnPpD0r4x6xyn0ftJ5
UBPnO1yNHcWI53lqxYODuGBYawQhZRsq96BicgaROzYsqbV/lTSm68OAgo5osrQIOAibDF
2Lsew9gjOoB2towz9CI4PpMnwy3ZjKJK+LA0N3pVzCkff9twbxjEP52uShTnwaHwcl4yGu
W53JBbTO2f7G0p3QvQxRoB2gCsIOzRYIvA4IObTxhdq+AqYDO4I2rpMG/ng3Jeh8Z0ZmB6
oXjMrprkfJnuHYLwzsdtEVEWY6JidJ9u/iB4Khs7P1gPXgOtMCj8lVn1Z02UQD/lI68Ynw
YbwjDB8WwAF3vvuww2U0NzoH+jZx2QJTJ1JDKlAAAAAwEAAQAAAQBy3oS2JE6e4uFZt41r
r2GLHSr9SNzsuj/OgqHdkPN3Cx/yRAZ6g+z2xb5hKGQ2ZfOlwQdPn/6lg3di2sZ7Nn5qPh
itgNC5qGJ/ZHnH/OJlpwZSiEOpTRcQAbLawkKAHgs8WjsahX/IW7yIsNsPkdqq4MIo+rVP
Z/fR3Y17PEdrLX35UZUZbxCmNg2dekarljWliVLKNPgwcb98Pkku9b0FHGsv0Sh40qGKih
Z/o9ZcgyvEBR7HL7yivkQm1NzoDU0TiuOkfvbCWMBaFfXmJCR6LsHo4JnMjYLbmyRLe7z+
D9oZ1hNf1zmP9UGrP+0MRw8n/4bBuFDZZkKaQyCqGqoBAAAAgQC8W+rRi34oxs9/oLEJDR
QMV40aqwX3yW90zfWz4bjFvCvxZr1jeiuoWRh1+xtTt5w460SSh55+IUDDjlc6TVguOP/8
pjf/WN1qxhKEovfZ0+U/CqI7Fv5snsdIa07Z85EmBHPHQt5Y5UmUF119hDCIAZNdug1yi5
J7PgDvi3vJjAAAAIEA4sxC1cF2g2B6IJKJYt1V6iDxRcNXTXvdf7REkc0E5f2AAyAz5x1U
CBwuuvutydEqytYAi4yMW9NP53kUgskNUIEdb60H0n2g6ZIecuiXGD9io3FTRc7COI94nB
4OVLuZORsHKzGKDvXfpim5iEIpZWYEz8UhVgeAStpnVkv+xOEAAACBAOCWckGDRi1b7B2Y
gd9KXLBHz8FFVr9h+z7EpSpHmrcSEqoJXqrE3BGI7wcFd0vTwSiEAMazga/I1U0OK6RHfs
/Vttg8wVqkV8GcQMHsxhxC7bwlb8z6hAafyDVoqaW0E577PMaob4zJj3mRLiChVdEKSW0m
ljQt8im3u5Eae2JFAAAAGHN1bmxpZ2h0anVzdGluQGdtYWlsLmNvbQEC
-----END OPENSSH PRIVATE KEY-----")


      # cocoapods()

      # 构建你的应用
      build_app(
          scheme: "github-actions-demo-ios",
          clean: true,
          export_method: "app-store",
          output_directory: "./build"
      )
      # 上传应用到AppStore
      upload_to_app_store(
            api_key: api_key,
            force: true, # Skip HTMl report verification
            skip_screenshots: true,
            skip_metadata: true,
            submit_for_review: false,
            precheck_include_in_app_purchases: false,
      )

  end



  desc "Push a new beta build to TestFlight"
  lane :beta do

    # app_store_connect_api_key
    # get_provisioning_profile

    # increment_build_number(
    #     xcodeproj: "github-actions-demo-ios.xcodeproj",
    #     build_number: date_based_build_number
    # )

    # build_app(
    #     scheme: "github-actions-demo-ios",
    #     configuration: "Release"
    # )
    # upload_to_testflight(skip_waiting_for_build_processing: true)


 



    # # 安装所有的Cocoapods依赖
    # cocoapods()

    # 增加构建号
    increment_build_number(
        xcodeproj: "github-actions-demo-ios.xcodeproj",
        build_number: date_based_build_number
    )


    # 构建你的应用
    build_app(
      scheme: "github-actions-demo-ios",
      clean: true,
      export_method: "app-store",
      output_directory: "./build"
    )

    # 发布到TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )


  end
end

def today_formatted
  Date.today.strftime('%Y%m%d')
end

def default_build_number
  "#{today_formatted}01"
end

def date_based_build_number
  current_build_number = get_build_number(xcodeproj: "buildandgrow-app-ios.xcodeproj")

  build_date = current_build_number[0..7]
  build_version = current_build_number[8..9]

  if (!build_date || !build_version) || (build_date.empty? || build_version.empty?)
    return default_build_number
  end

  begin
    build_date_object = Date.strptime(build_date, '%Y%m%d')
  rescue
    return default_build_number
  end


  if build_date_object >= Date.today
    new_version = build_version.to_i + 1
    return "#{today_formatted}%02d" % new_version
  end

  return default_build_number
end
